import pytest

from app.services.rag.query_router import (
    QueryIntent,
    QueryIntentRouter,
)
from app.services.vector.embedding_service import EmbeddingService


@pytest.fixture(scope="module")
def router():
    embedding_service = EmbeddingService(model_name="bge-small")
    return QueryIntentRouter(
        embedding_service,
        conversation_threshold=0.55,
        document_threshold=0.55,
    )


CONVERSATIONAL_CASES = [
    "hello",
    "hi",
    "hey there",
    "good morning",
    "good afternoon",
    "good evening",
    "how are you?",
    "how are you doing today?",
    "what's up?",
    "how's it going?",
    "thanks",
    "thank you",
    "thank you very much",
    "bye",
    "goodbye",
    "see you later",
    "nice to meet you",
    "have a good day",
    "good night",
    "greetings",
    "hello there",
    "hi there",
    "hey buddy",
    "morning!",
    "afternoon everyone",
    "evening folks",
    "wassup?",
    "howdy",
    "yo",
    "good to see you",
    "nice to talk to you",
    "pleased to meet you",
    "happy to help",
    "how have you been?",
    "how are things?",
    "what can you do?",
    "who are you?",
    "can you help me?",
    "hey, can we chat?",
    "good day",
    "good evening everyone",
    "hello friend",
    "hi friend",
    "hey friend",
    "good morning team",
    "good afternoon team",
    "good evening team",
    "thanks again",
    "many thanks",
    "much appreciated",
    "see ya",
    "talk to you later",
    "catch you later",
    "have a lovely day",
    "have a nice evening",
    "have a great day",
    "how are you feeling today?",
    "how's everything going?",
    "what's new?",
    "what are you up to?",
    "are you there?",
    "you there?",
    "can you hear me?",
    "hello again",
    "hi again",
    "good morning again",
    "nice to see you",
    "nice to meet you again",
    "happy Monday!",
    "happy Friday!",
    "hello there, how are you?",
    "hey, what's happening?",
    "hi, how is it going?",
    "good morning, friend",
    "great to see you",
    "good to know you",
    "hey there, buddy",
    "yo, what's up?",
    "hello, nice to meet you",
    "thank you so much",
    "thanks a lot",
    "appreciate it",
    "cheers",
    "good luck",
        "yo, what's good?",
    "sup?",
    "howdy partner",
    "g'morning",
    "afternoon!",
    "evenin'",
    "hey hey",
    "hiya",
    "how's life?",
    "what's happening?",
    "how are things going?",
    "long time no see",
    "glad to see you",
    "pleasure",
    "take care",
    "ciao",
    "later",
    "peace out",
    "have a good one",
    "cheers mate",
    "thanks a million",
    "appreciate ya",
    "you're awesome",
    "cool",
    "awesome",
    "nice",
    "great",
    "ok",
    "okay",
    "sure",
    "yeah",
    "nope",
    "maybe",
    "hello world",
    "hi there, how's your day?",
    "good morning, sunshine",
    "hey, what's new?",
    "how are you doing?",
    "are you awake?",
    "you there?",
    "can you hear me?",
    "hello, is anyone there?",
    "hey, can we talk?",
    "I need your help",
    "can you assist me?",
    "could you please help?",
    "I have a question",
    "quick question",
    "I'd like to ask something",
    "just checking in",
    "hope you're well",
    "hope you had a good day",
    "good night, sleep well",
    "sweet dreams",
    "see you tomorrow",
    "talk soon",
    "catch you on the flip side",
    
]

DOCUMENT_CASES = [
    "what does the document say about this?",
    "what are the main points discussed in the document?",
    "summarize the document",
    "what are the objectives described in the document?",
    "what does the PDF say about this topic?",
    "according to the document, what is this?",
    "explain this topic from the uploaded document",
    "give me a summary of the uploaded file",
    "extract the key ideas from this document",
    "what conclusions are mentioned in the document?",
    "tell me the main takeaways from the file",
    "what are the key findings in this paper?",
    "summarize the report for me",
    "what does this document say about the architecture?",
    "what are the major arguments in the document?",
    "summarise the uploaded document",
    "based on the document, what are the recommendations?",
    "what is described in the report?",
    "what does the uploaded file mention about this topic?",
    "can you explain the document in simpler words?",
    "please summarize the document for me",
    "what does the uploaded document say about the project timeline?",
    "give a concise summary of the PDF",
    "what are the most important details in the document?",
    "tell me the key insights from this report",
    "what does this file say about the requirements?",
    "according to the uploaded file, what are the risks?",
    "extract the summary from the document",
    "what are the main arguments in the report?",
    "what is this document discussing?",
    "give me the highlights from the report",
    "what are the recommendations in the document?",
    "can you explain the results section from the paper?",
    "what does the document mention about the methodology?",
    "tell me about the findings in the PDF",
    "summarize the uploaded document in plain English",
    "what key points are covered in this report?",
    "why was this document created?",
    "what is the main takeaway from the uploaded PDF?",
    "what are the conclusions in this file?",
    "can you break down the document section by section?",
    "what does the document say about the solution approach?",
    "what information is included in the uploaded document?",
    "summarize the architecture section of the document",
    "what are the important findings from the file?",
    "give me a short overview of this document",
    "what is explained in the uploaded report?",
    "what does the document highlight about the implementation?",
    "which risks are mentioned in the document?",
    "what are the assumptions discussed in the report?",
    "can you explain the uploaded paper in easier language?",
    "what are the main objectives captured in the document?",
    "what does the document say about the user requirements?",
    "please explain the uploaded document",
    "what details are provided in the PDF about the dataset?",
    "summarize the recommendations from the document",
    "what are the conclusions and recommendations in the report?",
    "can you tell me the core ideas of this document?",
    "what does the file discuss about scaling?",
    "what is the document trying to say?",
    "give me a summary of the uploaded report",
    "what are the critical points in this document?",
    "what insights are in the file?",
    "what does the document cover?",
    "what are the implications mentioned in this paper?",
    "summarise the report in a few bullet points",
    "what is the overview of the uploaded document?",
    "what were the main findings of the study?",
    "can you summarize the file content?",
    "what does the uploaded document mention about performance?",
    "what does the report say about the evaluation?",
    "what are the key takeaways from this paper?",
    "give me a detailed summary of the document",
    "what does this PDF talk about?",
    "what are the major sections in the document?",
    "can you explain the document in simpler terms?",
    "what is described in the uploaded file?",
    "what recommendations are listed in the report?",
    "what does the document state about the system design?",
    "tell me the main ideas in the uploaded document",
    "summarize the main points from the PDF",
    "what are the important details in the paper?",
    "what does the document say about the deployment plan?",
    "what are the benefits described in the report?",
    "can you explain the findings from the document?",
    "what are the deliverables mentioned in the file?",
    "what does the document mention about the timeline?",
    "what are the action items from the report?",
    "extract the key sections from the uploaded document",
    "summarize the document in plain English",
    "what are the issues discussed in the report?",
    "what are the expected outcomes mentioned in the document?",
    "what does the PDF say about the architecture and design?",
    "give me bullet points from the uploaded file",
    "what is the summary of the document?",
    "what does this document say about the requirements gathering phase?",
    "explain the key concepts in this report",
    "what did the document say about the security model?",
    "what are the major points in the uploaded paper?",

        "what are the limitations mentioned in the document?",
    "does the report discuss any risks?",
    "what is the methodology used in this paper?",
    "what data was collected for the study?",
    "how was the experiment designed?",
    "what are the statistical results?",
    "what do the figures show?",
    "can you interpret table 3?",
    "what are the author's conclusions?",
    "what future work is suggested?",
    "who are the authors?",
    "when was this document published?",
    "what is the title of the uploaded file?",
    "how many pages does the document have?",
    "what is the file size?",
    "list the sections of the document",
    "what is the abstract about?",
    "give me the introduction of the paper",
    "what is the background of the study?",
    "what problem does this document solve?",
    "what are the key contributions?",
    "compare the results with previous work",
    "what is the main hypothesis?",
    "what evidence supports the claims?",
    "are there any citations?",
    "what references are used?",
    "is there a bibliography?",
    "what is the appendix about?",
    "what does the document say about cost?",
    "what is the budget mentioned?",
    "what timeline is proposed?",
    "what are the deliverables?",
    "what are the success criteria?",
    "who is the target audience?",
    "what is the scope of the project?",
    "what are the assumptions?",
    "what constraints are mentioned?",
    "what are the dependencies?",
    "what is the implementation plan?",
    "what deployment strategy is suggested?",
    "what security measures are recommended?",
    "what performance metrics are used?",
    "what is the accuracy reported?",
    "how was the model trained?",
    "what hyperparameters were chosen?",
    "what is the error rate?",
    "what are the trade-offs?",
    "what are the alternatives considered?",
    "why was this approach chosen?",
    "what is the conclusion of the report?",
]

HYBRID_CASES = [
    "hello, can you explain this topic from the document?",
    "hi, what does the document say about this?",
    "good morning, can you explain this from the PDF?",
    "thanks, now explain this topic from the document",
    "hey, can you tell me what the uploaded document says about this?",
    "hello, what does this document say?",
    "hey, can you tell me what the PDF says about this?",
    "good evening, summarize the uploaded document for me",
    "hi there, can you explain the key points in this file?",
    "how are you? can you summarize the document for me?",
    "hey, can you walk me through the document summary?",
    "good morning, explain the main points from this report",
    "hello there, what does the document say about this issue?",
    "thanks, can you summarize the uploaded PDF for me?",
    "hi there! can you summarize the report for me?",
    "good evening, could you explain the main findings in the document?",
    "hello, please summarize the uploaded file and explain the main takeaways",
    "hey, what does the PDF say about this and can you explain it?",
    "good morning, can you tell me what the document mentions about this?",
    "thanks, now summarize the document and highlight the key points",
    "hello there, can you explain this from the uploaded file?",
    "good morning, can you summarize the paper for me?",
    "hi there, what does the document mention about the design?",
    "good evening, can you summarize the PDF and key findings?",
    "hey there, explain the uploaded document in simple language",
    "good morning, tell me what the report says about this feature",
    "how's it going? can you summarize the uploaded document for me?",
    "hello, can you tell me the key takeaways from this document?",
    "good evening, please explain the document in plain English",
    "good morning, can you explain the document in simpler terms?",
    "hey there, can you summarize the document and the key findings?",

    "hello, can you tell me about the results?",
    "hi, what does the file say about the timeline?",
    "good morning, please summarize the key findings",
    "hey, what's the main takeaway from the document?",
    "howdy, could you explain the methodology?",
    "hi there, I need a summary of the uploaded PDF",
    "greetings, can you list the conclusions?",
    "yo, what are the main points in the report?",
    "sup, what does the document cover?",
    "good evening, can you tell me the limitations?",
    "hey, what's in the document about the risks?",
    "hello, could you break down the document?",
    "hi, I need to understand the document's purpose",
    "good afternoon, what does the PDF say about costs?",
    "hiya, can you extract the key numbers?",
    "hey buddy, what are the recommendations?",
    "what's up? can you explain the document?",
    "how's it going? I need a summary of the file",
    "long time, no see. Can you summarize the report?",
    "good to see you, what does the document say?",
    "hey, can you give me an overview of the uploaded document?",
    "hello, I'm interested in the document's conclusions",
    "hi, can you please tell me what the document says about X?",
    "good morning, what are the main arguments in the paper?",
    "hey there, I'd like a brief summary of the document",
]

BORDERLINE_HYBRID_OR_DOCUMENT_CASES = [
    "hi, could you explain the results section from the uploaded paper?",
    "hello there, can you extract the main points from the document?",
    "hey, can you summarize the main findings in the report?",
    "good morning, what does this document say about the architecture?",
    "good day, can you tell me what the document says about this?",
    "hi, what are the main points of the uploaded report?",
    "hey, what conclusions are mentioned in the document?",
    "hi, what does the PDF say about the security model?",
    "hello, I need the document summary and the main objectives",
    "good afternoon, what are the major arguments in the document?",
    "thanks, I want a concise summary of the uploaded paper",
    "hi, can you tell me what this PDF says about requirements?",
    "hello there, can you extract the main points from the document?",
    "good evening, could you summarize the report and the recommendations?",
    "hi, what are the major points in the uploaded document?",
    "thanks, could you explain the recommendations from the report?",
    "hey buddy, summarize the file and explain the recommendations",
    "thanks, can you give me the main findings from the report?",
    "hello, can you break down the main points in the uploaded report?",
    "hello, tell me what the uploaded file says about the project timeline",
    "hello, I need the document summary and the main objectives",
    "good evening, could you summarize the report and the recommendations?",
    "thanks, I want a concise summary of the uploaded paper",
]

AMBIGUOUS_CASES = [
    "write a poem about the ocean",
    "what is the weather like today?",
    "how do I fix a broken laptop battery?",
    "tell me a joke",
    "can you help me create a study plan?",
    "what is 42 times 17?",
    "can you recommend a good restaurant nearby?",
    "what is the capital of France?",
    "give me ideas for a birthday party",
    "how do I learn Python faster?",
    "what is the best way to improve my sleep?",
    "what are the benefits of exercise?",
    "what is the difference between SQL and NoSQL?",
    "can you explain machine learning in simple terms?",
    "how do I prepare for a job interview?",
    "what are some healthy breakfast ideas?",
    "what should I do if my code is failing?",
    "how do I write a good project plan?",
    "how can I stay productive while working from home?",
    "what should I eat for lunch?",
    "what is the best way to learn data science?",
    "what is the fastest way to learn English?",
    "how do I keep my motivation high?",

    "what is the meaning of life?",
    "tell me a story",
    "write a poem",
    "sing a song",
    "what movies are playing?",
    "how to bake a cake?",
    "what is the best phone to buy?",
    "should I invest in crypto?",
    "how to lose weight fast?",
    "what is the weather in New York?",
    "give me a recipe for pasta",
    "how do I change a tire?",
    "what is the capital of Australia?",
    "who won the world cup?",
    "what is the latest news?",
    "can you do my homework?",
    "solve this math problem: 2+2",
    "what is the square root of 144?",
    "translate 'hello' to Spanish",
    "what is the time?",
    "set a timer for 10 minutes",
    "play some music",
    "open the window",
    "turn on the lights",
    "remind me to call mom",
    "what's on my calendar?",
    "send an email to John",
    "how many planets are there?",
    "what is a black hole?",
    "how does photosynthesis work?",
    "what is the best diet?",
    "how to meditate?",
    "what is the secret to happiness?",
    "how to be successful?",
    "what is love?",
]


@pytest.mark.parametrize("query", CONVERSATIONAL_CASES)
def test_conversational_queries(router, query):
    result = router.classify(query)
    assert result.intent == QueryIntent.CONVERSATIONAL


@pytest.mark.parametrize("query", DOCUMENT_CASES)
def test_document_queries(router, query):
    result = router.classify(query)
    assert result.intent == QueryIntent.DOCUMENT


@pytest.mark.parametrize("query", HYBRID_CASES)
def test_hybrid_queries(router, query):
    result = router.classify(query)
    assert result.intent == QueryIntent.HYBRID


@pytest.mark.parametrize("query", BORDERLINE_HYBRID_OR_DOCUMENT_CASES)
def test_borderline_hybrid_or_document_queries(router, query):
    result = router.classify(query)
    assert result.intent in {QueryIntent.HYBRID, QueryIntent.DOCUMENT}


@pytest.mark.parametrize("query", AMBIGUOUS_CASES)
def test_ambiguous_real_world_queries(router, query):
    result = router.classify(query)
    assert result.intent in {
        QueryIntent.UNKNOWN,
        QueryIntent.CONVERSATIONAL,
        QueryIntent.DOCUMENT,
    }


def test_router_rejects_empty_query(router):
    result = router.classify("   ")
    assert result.intent == QueryIntent.UNKNOWN
    assert result.confidence == 0.0


def test_router_handles_mixed_case_and_punctuation_variants(router):
    variants = [
        "HELLO, CAN YOU EXPLAIN THIS TOPIC FROM THE DOCUMENT?",
        "Good Morning! What does the PDF say about this?",
        "Hi there, summarize the uploaded report for me.",
        "THANKS, now explain this topic from the uploaded document.",
        "hey... can you tell me what the document says about this?",
    ]

    for query in variants:
        result = router.classify(query)
        assert result.intent == QueryIntent.HYBRID


def test_router_preserves_expected_confidence_shape(router):
    result = router.classify("hello there, can you summarize this document for me?")

    assert result.intent == QueryIntent.HYBRID
    assert isinstance(result.confidence, float)
    assert set(result.scores).issuperset({"conversation", "document", "hybrid"})
